
version: '3.8'

volumes:
  myvol:
services:
  frontend:
    image: parte15/netflix-frontend:${IMAGE_TAG:-latest}
    ports:
      - "9090:9090"
    volumes:
      - myvol:/tmp
    restart: always

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=netflix_pass
      - MYSQL_DATABASE=netflix_db
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    image: parte15/netflix-backend:${IMAGE_TAG:-latest}
    build: ./backend
    container_name: netflix-backend
    ports:
      - "5000:5000"
    restart: always
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=netflix_pass
      - DB_NAME=netflix_db
    depends_on:
      - db

